name: Update Cache Data

on:
  schedule:
    # 每隔30分钟运行一次 (*/30 表示每30分钟)
    - cron: '*/30 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run cache update script
      run: python update_cache_github.py
      
    - name: Check if cache.json was updated
      id: check_changes
      run: |
        if git diff --quiet cache.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add cache.json
        git commit -m "Auto-update cache.json - $(date '+%Y-%m-%d %H:%M:%S UTC')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: No changes detected
      if: steps.check_changes.outputs.changed == 'false'
      run: echo "No new data to update in cache.json" 