name: Update Cache Data

on:
  schedule:
    # 每隔30分钟运行一次 (*/30 表示每30分钟)
    - cron: '*/30 * * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write  # 允许写入仓库内容

jobs:
  update-cache:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # 获取完整历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run cache update script
      run: python update_cache_github.py
      
    - name: Check if cache.json was updated
      id: check_changes
      run: |
        if git diff --quiet cache.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.changed == 'true'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-update cache.json - $(date '+%Y-%m-%d %H:%M:%S UTC')"
        file_pattern: cache.json
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
    
    - name: No changes detected
      if: steps.check_changes.outputs.changed == 'false'
      run: echo "No new data to update in cache.json" 